### ISSUE TITLE
Simplify install instructions when you do not have write access to Sage install

### ISSUE THREAD

**Issue by williamstein** [nbruin/RiemannTheta#2]
I think you can still pip install this package just fine without write access to the Sage install and without having to git clone and use setup.py.  Just put `--user` after install in your first pip command.   See:
```sh
~$ sage --pip install --user git+https://github.com/nbruin/RiemannTheta
Collecting git+https://github.com/nbruin/RiemannTheta
  Cloning https://github.com/nbruin/RiemannTheta to /tmp/pip-req-build-15bubehk
  Running command git clone -q https://github.com/nbruin/RiemannTheta /tmp/pip-req-build-15bubehk
Building wheels for collected packages: RiemannTheta
  Building wheel for RiemannTheta (setup.py) ... done
  Created wheel for RiemannTheta: filename=RiemannTheta-0.0.1-cp39-cp39-linux_x86_64.whl size=626075 sha256=cc1e95c356a87dc683b6cc557c0c74310a6992c8f703361dfa945c42827e5245
  Stored in directory: /tmp/pip-ephem-wheel-cache-mk4wt2pq/wheels/0c/cf/76/1b9a3ada228198faa253d884b2066beedb7a12519358d05c0f
Successfully built RiemannTheta
Installing collected packages: RiemannTheta
Successfully installed RiemannTheta-0.0.1
~$ sage
┌────────────────────────────────────────────────────────────────────┐
│ SageMath version 9.3, Release Date: 2021-05-09                     │
│ Using Python 3.9.2. Type "help()" for help.                        │
└────────────────────────────────────────────────────────────────────┘
sage: from riemann_theta.riemann_theta import RiemannTheta                                       
sage:  
```

**Comment by williamstein** [comment]
The small drawback is this, which is not surprising and should be harmless:
```python
~$ python3
Python 3.9.5 (default, Jun 23 2021, 01:03:04) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from riemann_theta.riemann_theta import RiemannTheta        
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "riemann_theta/riemann_theta.pyx", line 1, in init riemann_theta.riemann_theta
ModuleNotFoundError: No module named 'sage.structure'
>>> 
```

**Comment by nbruin** [comment]
Hi William,
Thanks for looking into this! I thought/hoped `--user` would work. However, when I do this I get:
```
$ sage --pip install --user git+https://github.com/nbruin/RiemannTheta
ERROR: Can not perform a '--user' install. User site-packages are not visible in this virtualenv.
``` 
On that same system (FC 33), installing packages with `--user` under the standard python works well. That's why I interpreted this as sage's python environment generally not permitting user-installed packages. One can of course manually change `sys.path`, but I don't know how to write general instructions for that. I tested this with SageMath 9.4. And since currently people are very actively fiddling with the python environment and packaging of sage, I imagine something might have changed from 9.3 to 9.4.
```
$ sage --python3 -c "import sys; print(sys.path)"
['', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/usr/local/sage/sage-git/local/lib64/python3.9/site-packages', '/usr/local/sage/sage-git/local/lib/python3.9/site-packages']
$ python3 -c "import sys; print(sys.path)"
['', '/usr/lib64/python39.zip', '/usr/lib64/python3.9', '/usr/lib64/python3.9/lib-dynload', '/home/nbruin/.local/lib/python3.9/site-packages', '/home/nbruin/pollscore', '/usr/lib64/python3.9/site-packages', '/usr/lib/python3.9/site-packages']
```
As you can see, my normal python environment picks up `$HOME/.local` (as well as a package that's been installed with `--edit`), but none of that makes it into the sage python environment. In fact, what IS a little worrisome is that sage's python still happily includes the system python libraries as well!

**Comment by williamstein** [comment]
Nevermind -- I forgot what a mess pip packaging still is with Python, since I've got used to using npm and node.js the last few years.      pip is much better than it used to be (especially before it existed), but it's still kind of ridiculous.
